apiVersion: v1
data:
  config.yaml: |
    redis:
      host: zerok-cli-redis-master.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      db: 7
kind: ConfigMap
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
  namespace: zk-client

