apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zk-wsp.fullname" . }}-configmap
  labels:
  {{- include "zk-wsp.labels" . | nindent 4 }}
data:
  wsp-config.yaml: |-
    host: localhost
    port : 8987
    timeout : 3000
    target:
      url: "wss://api.{{ .Values.global.zkcloud.host }}:{{ .Values.global.zkcloud.port }}/register"
      clusterSecretName: cluster-info
      clusterKeyData: clusterKey
      clusterKeyNamespace: zk-client
      maxRetries: 3
    poolidlesize: 5
    poolmaxsize: 100
