routes:
  zkCloudAddr: ""
deployment:
  replicas: 1
  zkWspClient:
    image:
      repository: nginx
      tag: dev
    imagePullPolicy: Always
kubernetesClusterDomain: cluster.local
zkWspClient:
  ports:
  - port: 8987
    protocol: TCP
    targetPort: 8987
  type: ClusterIP
