apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zk-axon.fullname" . }}-zk-axon
  labels:
    app: zk-axon
  {{- include "zk-axon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zkAxon.replicas }}
  selector:
    matchLabels:
      app: zk-axon
    {{- include "zk-axon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: zk-axon
      {{- include "zk-axon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: PL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: postgres
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ index .Values "global" "zk-axon" "repo" }}:{{ index .Values "global" "zk-axon" "tag"  }}"
        imagePullPolicy: {{ .Values.zkAxon.zkAxon.imagePullPolicy }}
        name: zk-axon
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          successThreshold: 3
        resources: {{- toYaml .Values.zkAxon.zkAxon.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /zk/config
          name: config
      volumes:
      - configMap:
          name: {{ include "zk-axon.fullname" . }}-zk-axon
        name: config