apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zk-axon.fullname" . }}-zk-axon
  labels:
    app: zk-axon
  {{- include "zk-axon.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.zkAxon.configYaml | toYaml | indent 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zk-axon.fullname" . }}-zk-axon
  labels:
    app: zk-axon
  {{- include "zk-axon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zkAxon.type }}
  selector:
    app: zk-axon
  {{- include "zk-axon.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.zkAxon.ports | toYaml | nindent 2 -}}